linters:
  enable:
    - goconst
    - gocritic
    - gofmt
    - govet
    - prealloc
    - unconvert
    - errcheck
    - ineffassign
    - typecheck
    - containedctx
    - usetesting
    - unused