lint:
	golangci-lint run ./config/... ./database/... ./hasura/... ./node/... ./prometheus/... ./tools/... ./tzkt/...

test:
	go test ./config/... ./database/... ./hasura/... ./node/... ./prometheus/... ./tools/... ./tzkt/...